### ISSUE TITLE
Armor broken

### ISSUE THREAD

**Issue by Scrincz** [lishaodong/Syndria#11]
When taking off and putting on armor it will only say +(hp or piece) and -(hp of piece) when you take it off and on but will not display the other attributes like block dodge and things that the armor has. It used to display all the enchantments when you put on a piece.

**Comment by lishaodong** [comment]
replace all scheduleAsyncRepeatingTask to scheduleSyncRepeatingTask

**Comment by lishaodong** [comment]
should fixed
