### ISSUE TITLE
Banks not working

### ISSUE THREAD

**Issue by Scrincz** [lishaodong/Syndria#9]
banks no longer work you cannot deposit gems or remove armor or put armor in and if you are not op you cannot even open them

**Comment by Scrincz** [comment]
it was a bug for me but you cannot open them if you are not op

**Comment by lishaodong** [comment]
could you give me the location (x,y,z) of the banks. I don't where to test it.

**Comment by lishaodong** [comment]
@Scrincz

**Comment by Scrincz** [comment]
The banks are enderchests, so u could  just place a enderchests drop itself
and try it

**Comment by lishaodong** [comment]
@Scrincz now bank should works. and now the icon of notes is incorrect. correct that later
